---
  - name: copy {{ component }} systemd service
    ansible.builtin.template:
      src: systemd.service.j2
      dest: /etc/systemd/system/{{ component }}.service
      notify:
         - daemon-reload

  - name: start service
    ansible.builtin.service:
      name: "{{ component }}"
      state: restarted
      enabled: yes
      